---
title: "data_tidy"
author: "Tianshu Liu"
date: "2022-09-27"
output: html_document
---

```{r,message=FALSE}
library(tidyverse)
options(tibble.print_min = 5)
```


```{r pivot_longer, message=FALSE}
pulse_df = haven::read_sas('data/public_pulse_data.sas7bdat') %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = 'visit',
    values_to = 'bdi',
    names_prefix = "bdi_score_"
  ) %>%
  mutate(
    visit = replace(visit, visit == 'bl', '00m'),
    visit = factor(visit)
  ) %>%
  arrange(id,visit) %>%
  relocate(visit, .after = id)

pulse_df
```

```{r litter_data, message=FALSE}
litter_data = read_csv('data/FAS_litters.csv') %>%
  janitor::clean_names() %>%
  select(litter_number, ends_with("weight")) %>% 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = 'gd',
    values_to = 'weight'
  ) %>%
  mutate(
    gd = recode(gd, 'gd0_weight' = 0, 'gd18_weight' = 18)
  )
litter_data
```

```{r pivot_wider}
analysis_results = tibble(
  group = c('treatment', 'treatment', 'placebo', 'placebo'),
  time = c('pre', 'post', 'pre', 'post'),
  mean = c(4, 8, 3.5, 4)
) %>%
  pivot_wider(
    names_from = 'time',
    values_from = 'mean'
  )

analysis_results
```

```{r bind_rows}
fellowship_ring = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = 'gender',
    values_to = 'word'
  ) %>%
  mutate(
    race = str_to_lower(race)
  )
```

```{r}
pups = 
  read_csv('data/FAS_pups.csv') %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex, '1' = 'male', '2' = 'female')
  )
```


