---
title: "data_manipulation with 'dplyr'"
output: github_document
date: "2022-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6, 
  fig.asp = .6, 
  out.width = "90%"
)
library(tidyverse)
```

```{r import_data}
litters_data = read_csv("data/FAS_litters.csv", col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)
pups_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

## Select Cols
```{r}
select(litters_data, group, litter_number)
select(litters_data, group:gd_of_birth)
select(litters_data, -pups_survive)
select(litters_data, New_Group = group, LiTtEr_NuMbEr = litter_number)
select(litters_data, starts_with("gd"))
select(litters_data, ends_with("t"))
select(litters_data, -group, litter_number, gd_of_birth, everything())
```


## Filter
```{r}
filter(pups_data, sex == 1)
filter(pups_data,  sex == 2, pd_walk < 11)
filter(pups_data,  sex == 2, pd_walk < 11) %>% select(starts_with("pd"))
filter(pups_data,  sex != 1 & pd_ears > 4)
filter(pups_data,  !(sex == 1 & pd_walk != 10))
filter(pups_data,is.na(pd_eyes))
filter(pups_data, pd_ears %in% c(2, 3, 4))
drop_na(pups_data, pd_ears, pd_eyes)
drop_na(pups_data, pd_ears, pd_pivot) %>% filter(is.na(pd_eyes))
```

## Mutate: add or remove cols
```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

## Pips: %>%

```{r}
litters_data_clean_without_pips = 
  drop_na(
    mutate(
      select(
        janitor::clean_names(
          read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
          ), 
      -pups_survive
      ),
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ),
  wt_gain
  )

#litters_data_clean_without_pips

litters_data_with_pips = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
#litters_data_with_pips
```

